# https://github.com/P3TERX/ActionsVM

name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Start SSH via ngrok
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: 1n6ghgHelnLOXRc2eF9jbDvd8EB_M3cedNzu4JUte7Kmm3qB
        NGROK_REGION: jp
        SSH_PASSWORD: a
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run End Script
      run: source ubuntu-end.sh
